### ISSUE TITLE
What is the superiority of P4 over OpenCl?

### ISSUE THREAD

**Issue by ali64Mon** [p4lang/p4factory#103]
Hi everybody,

I am new to P4 and I am trying to find a topic related to P4 for my internship project. In this regard, I have some questions:
1. I know Opencl is a framework for writing programs that execute across heterogeneous platforms consisting of central processing units (CPUs), graphics processing units (GPUs), digital signal processors (DSPs), field-programmable gate arrays (FPGAs) and other processors or hardware accelerators. What is the benefit of using P4 over OpenCl in case of packet processing.
2. Do you have any idea about a topic related to P4 for my internship project?

Regards,

**Comment by VincentSC** [comment]
P4 can best be seen as a Domain Specific Language. I've looked a bit into it, and the language can possibly be compiled down to a task-based OpenCL program - at least I can manually translate P4 to an OpenCL program that runs on the FPGA.

**Comment by chkim4142** [comment]
Hi, I'd suggest you bring these questions to p4-discuss@lists.p4.org, where active P4-related discussions are arising.
