### ISSUE TITLE
p4factory/mininet/openflow_l2.py execution problem

### ISSUE THREAD

**Issue by LucasShih** [p4lang/p4factory#117]
I have already run "make bm-p4ofagent PLUGIN_OPENFLOW=1" command in p4factory/targets/switch to build the switch target with the Openflow Agent, but when I execute the openflow_l2.py there is the error message:
**Traceback (most recent call last):
  File "./openflow_l2.py", line 190, in <module>
    main()
  File "./openflow_l2.py", line 179, in main
    configure_switch()
  File "./openflow_l2.py", line 122, in configure_switch
    setup_bd(client, conn_mgr)
  File "./openflow_l2.py", line 75, in setup_bd
    action_spec = dc_set_bd_action_spec_t(
NameError: global name 'dc_set_bd_action_spec_t' is not defined**

How could I fix it ? Thank you!

**Comment by pierce-m** [comment]
Thanks for catching this. It's fixed in pull request 118.

**Comment by LucasShih** [comment]
Thank you, that it works!
