### ISSUE TITLE
target switch for bmv2 make bm error

### ISSUE THREAD

**Issue by sunnogo** [p4lang/p4factory#122]
`p4factory/targets/switch/bmv2/README.md` shows we can build bmv2 switch through `make bm`. However submodule bmv2 uses autoconf tool, and error occurs as no makefile found.

```
sunnogo@sunyongfeng:~/research/p4/p4factory/targets/switch/bmv2$ make bm
make -C /home/sunnogo/research/p4/p4factory/submodules/bm
make[1]: Entering directory `/home/sunnogo/research/p4/p4factory/submodules/bm'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/home/sunnogo/research/p4/p4factory/submodules/bm'
make: *** [/home/sunnogo/research/p4/p4factory/targets/switch/bmv2/switch_bmv2] Error 2
```

After run `./autogen` and `./configure` in `p4factory/submodules/bm`, it works fine when `make bm` in `p4factory/targets/switch/bmv2/`.

**Comment by antoninbas** [comment]
Hi, I am not sure I understand this, as the [p4factory README] (https://github.com/p4lang/p4factory#quickstart) does say that you need to run `./autogen.sh` and `./configure` in the p4factory root, which will trigger these commands in the bm submodule.

**Comment by sunnogo** [comment]
Sorry for not pay attention to the p4facory outer README. It works fine after following the list command.
