### ISSUE TITLE
Install script for Ubuntu 14.04 fails because of thrift

### ISSUE THREAD

**Issue by zorun** [p4lang/p4factory#143]
The install script `install_deps.sh` fails on Ubuntu 14.04 when either Java or Haskell is installed.

The reason is that when compiling thrift 0.6.2, it will try to build bindings for all languages that are currently installed on the system.  The problem is, haskell and java bindings fail to build.

Since I think most language bindings are not needed for P4, is it possible to deactivate all unneeded languages?  By default, thrift tries to build them all:

```
./configure --help
  --with-qt4              build the Qt library [default=yes]
  --with-c_glib           build the C (GLib) library [default=yes]
  --with-csharp           build the C# library [default=yes]
  --with-java             build the Java library [default=yes]
  --with-erlang           build the Erlang library [default=yes]
  --with-nodejs           build the Nodejs library [default=yes]
  --with-lua              build the Lua library [default=yes]
  --with-python           build the Python library [default=yes]
  --with-perl             build the Perl library [default=yes]
  --with-php              build the PHP library [default=yes]
  --with-php_extension    build the PHP_EXTENSION library [default=yes]
  --with-ruby             build the Ruby library [default=yes]
  --with-haskell          build the Haskell library [default=yes]
  --with-go               build the Go library [default=yes]
  --with-d                build the D library [default=yes]
```

**Comment by huang362432** [comment]
so what should we do?

**Comment by antoninbas** [comment]
If this happens to you. You can always edit the `install_deps.sh` script locally to modify the `configure` command and disable the language bindings you do not need.
