### ISSUE TITLE
simple router make.

### ISSUE THREAD

**Issue by kzhang43** [p4lang/p4factory#144]
When I try to make https://github.com/p4lang/p4factory/tree/master/targets/simple_router
I get these errors? How do I fix them? 

/home/p4/p4factory/submodules/p4c-behavioral/p4c_bm/shell.py p4src/simple_router.p4 --gen-dir=/home/p4/p4factory/targets/simple_router/build//bm/ --thrift --public-inc-path=/home/p4/p4factory/targets/simple_router/build//inc/p4_sim --p4-prefix=simple_router 
WARNING: Couldn't open 'parser.out'. [Errno 13] Permission denied: '/home/p4/switch/p4c-bm/src/p4-hlir-v1.1/p4_hlir/frontend/parser.out'
WARNING: Token 'PPHASH' defined, but not used
WARNING: There is 1 unused token
Generating LALR tables
WARNING: 2 shift/reduce conflicts
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 19 : Syntax error while parsing at token dstAddr (ID)
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 19 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 20 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 21 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 27 : Syntax error while parsing at token version (ID)
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 27 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 28 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 29 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 30 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 31 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 32 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 33 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 34 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 35 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 36 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 37 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/includes/headers.p4 at line 38 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/simple_router.p4 at line 26 : Syntax error while parsing at token nhop_ipv4 (ID)
parse error in file /home/p4/p4factory/targets/simple_router/p4src/simple_router.p4 at line 26 : invalid field declaration
parse error in file /home/p4/p4factory/targets/simple_router/p4src/simple_router.p4 at line 32 : Syntax error while parsing at token nhop_ipv4 (ID)
parse error in file /home/p4/p4factory/targets/simple_router/p4src/simple_router.p4 at line 32 : Invalid param list for action function (
parse error in file /home/p4/p4factory/targets/simple_router/p4src/simple_router.p4 at line 49 : Syntax error while parsing at token dmac (ID)
parse error in file /home/p4/p4factory/targets/simple_router/p4src/simple_router.p4 at line 49 : Invalid param list for action function (
parse error in file /home/p4/p4factory/targets/simple_router/p4src/simple_router.p4 at line 64 : Syntax error while parsing at token smac (ID)
parse error in file /home/p4/p4factory/targets/simple_router/p4src/simple_router.p4 at line 64 : Invalid param list for action function (
25 errors during parsing
Interrupting compilation
Error while building HLIR
/home/p4/p4factory/submodules/p4c-behavioral/p4c-bm.mk:96: recipe for target '/home/p4/p4factory/targets/simple_router/build//bm/thrift/mc_pd_rpc.thrift' failed
make: *** [/home/p4/p4factory/targets/simple_router/build//bm/thrift/mc_pd_rpc.thrift] Error 1

**Comment by antoninbas** [comment]
I believe someone had the same problem as you on the p4-dev mailing list (http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2016-May/000306.html) and solved the issue by removing a few files manually.
Also, I need to point out that the P4 software switch you are using here (p4c-behavioral) is being deprecated and replaced by a new version (https://github.com/p4lang/behavioral-model)

**Comment by antoninbas** [comment]
Related to #162?
