### ISSUE TITLE
error while running ./behavioral-model

### ISSUE THREAD

**Issue by underriver** [p4lang/p4factory#146]
y@y-Lenovo:~/p4factory/targets/basic_routing$ sudo ./behavioral-model 
[sudo] y 的密码： 
No PD RPC server address specified, using 127.0.0.1:9090
No listener specified, switch will run in standalone mode

P4 Program:  basic_routing

Starting RPC server on port 9090
bmi_port_interface_add(port_mgr, veth_name, n_veth, pcap_filename): ERROR -1 at main.c:434y@y-Lenovo:~/p4factory/targets/basic_routing$

**Comment by antoninbas** [comment]
You already asked this question here: https://github.com/p4lang/behavioral-model/issues/166
The answer is the same. Are you sure you have created the veth interfaces successfully using this script: https://github.com/p4lang/p4factory/blob/master/tools/veth_setup.sh

**Comment by underriver** [comment]
thanks，


发自 网易邮箱大师
On 07/26/2016 00:47, Antonin Bas wrote:

You already asked this question here: p4lang/behavioral-model#166
The answer is the same. Are you sure you have created the veth interfaces successfully using this script: https://github.com/p4lang/p4factory/blob/master/tools/veth_setup.sh

**Comment by lukewen427** [comment]
I got the same problem on my docker container.  I do run: sudo p4factory/tools/veth_setup.sh, before execute the behavioral-model 

root@16f97d81ffe0:/P4/p4factory/targets/basic_routing# ./behavioral-model 
No PD RPC server address specified, using 127.0.0.1:9090
No listener specified, switch will run in standalone mode

P4 Program:  basic_routing

Starting RPC server on port 9090
bmi_port_interface_add(port_mgr, veth_name, n_veth, pcap_filename): ERROR -1 at main.c:434
