### ISSUE TITLE
INT feature fails to build

### ISSUE THREAD

**Issue by familysingh** [p4lang/p4factory#151]
I used the instructions in the README.md file for the INT code at the URL below.

https://github.com/p4lang/p4factory/tree/master/apps/int

The code fails to build with a Thrift error.  I am using the correct version of Linux kernel (4.2.0-42-generic) and Ubuntu 15.10.  

My P4 factory install worked fine and tested OK.  The Docker install tested OK as well. 

However, I just can't get "sudo make docker-image" to work and it complains that Thrift.h is not installed but I have installed Thrift.  The error is below. 

"configure: error: Thrift headers not found. Install Thrift from http://thrift.apache.org/docs/install/"

It would also be good to add notes to the INT README.md file as to why Docker is needed.   Is it to replace a VM for Mininet use?  Also, many instructions need sudo privilege to execute but the README.md file does not include the sudo in the notes.

**Comment by herlenashavi** [comment]
Hi,
Please follow the instructions in the README in the URL below.

https://github.com/p4lang/ntf/tree/master/apps/int
https://github.com/p4lang/ntf

I encourage you to read both the READMEs before proceeding with the installation. The INT demo scripts creates a topology of hosts and containerized BMv2 switches instead of the vanilla switch  that's baked into mininet. That's the reason you need docker installed. Also, the readme includes the ubuntu version that the demo has been tested with and the kernel version needed for the VXLAN-GPE drivers. Let me know in case you run into any issues.

Thanks,
Avinash

**Comment by familysingh** [comment]
Avinash,
In my Issues case filed, I have already said, I first installed Docker and tested that the Docker install works.  I also installed the p4 factory and tested it to work.   Then I used the instructions in the INT README.txt file and those instructions fails to build the docker-image.  This is why I filed the issue.
Thanks,
Hemant 

    On Tuesday, August 23, 2016 6:55 PM, Avinash Herle <notifications@github.com> wrote:
 

 Hi,
Please follow the instructions in the README in the URL below.https://github.com/p4lang/ntf/tree/master/apps/int
https://github.com/p4lang/ntfI encourage you to read both the READMEs before proceeding with the installation. The INT demo scripts creates a topology of hosts and containerized BMv2 switches instead of the vanilla switch that's baked into mininet. That's the reason you need docker installed. Also, the readme includes the ubuntu version that the demo has been tested with and the kernel version needed for the VXLAN-GPE drivers. Let me know in case you run into any issues.Thanks,
Avinash—

**Comment by herlenashavi** [comment]
Hemant,
The links I added in my comment are of a different repository. The INT demo has been moved to the Network Test Framework(NTF) repo. Let me know in case you run into any issue while running the demo on that repo.

Thanks,
Avinash

**Comment by familysingh** [comment]
Let me look into the NTF repo and test it tonight and get back to you.  I am on the East coast in Boston suburbs.
Thanks,
Hemant


    On Tuesday, August 23, 2016 7:08 PM, Avinash Herle <notifications@github.com> wrote:
 

 Hemant,
The links I added in my comment are of a different repository. The INT demo has been moved to the Network Test Framework(NTF) repo. Let me know in case you run into any issue while running the demo on that repo.Thanks,
Avinash—

**Comment by familysingh** [comment]
Do note from the Issues case, I am using Ubuntu 15.10 and a linux kernel in 4.2.0-42-generic.  Please let me know if vxlan has an issue with the 4.2.0-42-generic kernel. 
thanks,
Hemant

    On Tuesday, August 23, 2016 7:08 PM, Avinash Herle <notifications@github.com> wrote:
 

 Hemant,
The links I added in my comment are of a different repository. The INT demo has been moved to the Network Test Framework(NTF) repo. Let me know in case you run into any issue while running the demo on that repo.Thanks,
Avinash—

**Comment by herlenashavi** [comment]
The readme includes the ubuntu version that the demo has been tested with and the kernel version needed for the VXLAN-GPE drivers. You will need kernel version 3.19 for the VXLAN-GPE drivers as mentioned in the readme. 

https://github.com/p4lang/ntf/tree/master/apps/int

**Comment by familysingh** [comment]
Hi Avinash,
I know about kernel 3.19 and Ubuntu 14.x that have to be used with INT.
However, I am trying to make my environment work.  Also, for ubuntu 15.10, this step suggested at the INT URL does not work.  The package is not found for 15.10 Ubuntu.
sudo apt-get install linux-generic-lts-vivid
I looked a the Linux kernel commits and changed a few kernel .h files for 4.2.0-42-generic on my ubuntu15.10.  Vxlan-gpe built fine and the driver has been installed.  Now I am stuck at the step below.
This is the command which has failed while working with ntf and ntf's README file. 
sudo ./run_build_submodules.sh

The failure is included below.  p4_prefix2.cpp is related to the failure.
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I/ntf/bmv2/../../switch/p4-build/bmv2 -I.. -I/ntf/bmv2/install/include -I./switch/ -I./pd_thrift_gen/gen-cpp/ -DHOST_BYTE_ORDER_CALLER -DSWITCHAPI_ENABLE -DSWITCHSAI_ENABLE -DSWITCHLINK_ENABLE -std=c++11 -MT pd_thrift_gen/gen-cpp/p4_prefix2.lo -MD -MP -MF pd_thrift_gen/gen-cpp/.deps/p4_prefix2.Tpo -c pd_thrift_gen/gen-cpp/p4_prefix2.cpp  -fPIC -DPIC -o pd_thrift_gen/gen-cpp/.libs/p4_prefix2.og++: internal compiler error: Killed (program cc1plus)Please submit a full bug report,with preprocessed source if appropriate.See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.Makefile:789: recipe for target 'pd_thrift_gen/gen-cpp/p4_prefix2.lo' failedmake[7]: *** [pd_thrift_gen/gen-cpp/p4_prefix2.lo] Error 1make[7]: Leaving directory '/ntf/bmv2/build/switch/p4-build/bmv2'Makefile:972: recipe for target 'all-recursive' failedmake[6]: *** [all-recursive] Error 1make[6]: Leaving directory '/ntf/bmv2/build/switch/p4-build/bmv2'Makefile:570: recipe for target 'all' failedmake[5]: *** [all] Error 2make[5]: Leaving directory '/ntf/bmv2/build/switch/p4-build/bmv2'Makefile:424: recipe for target 'all-recursive' failedmake[4]: *** [all-recursive] Error 1make[4]: Leaving directory '/ntf/bmv2/build/switch/p4-build'Makefile:354: recipe for target 'all' failedmake[3]: *** [all] Error 2make[3]: Leaving directory '/ntf/bmv2/build/switch/p4-build'Makefile:457: recipe for target 'all-recursive' failedmake[2]: *** [all-recursive] Error 1make[2]: Leaving directory '/ntf/bmv2/build/switch'Makefile:387: recipe for target 'all' failedmake[1]: *** [all] Error 2make[1]: Leaving directory '/ntf/bmv2/build/switch'Makefile.bmv2:60: recipe for target 'driver-compile' failedmake: *** [driver-compile] Error 2
Thanks,
Hemant

 

    On Tuesday, August 23, 2016 7:32 PM, Avinash Herle <notifications@github.com> wrote:
 

 The readme includes the ubuntu version that the demo has been tested with and the kernel version needed for the VXLAN-GPE drivers. You will need kernel version 3.19 for the VXLAN-GPE drivers as mentioned in the readme. https://github.com/p4lang/ntf/tree/master/apps/int—

**Comment by familysingh** [comment]
Avinash,
Please close the case because the failure I emailed you this morning is due to lack of memory with the g++ compiler crashing.  I don't want to hold up resources at Barefoot for this issue.  I will continue to build and test and if I have any issues, I will let you know.  
Thanks,
Hemant 

    On Tuesday, August 23, 2016 7:32 PM, Avinash Herle <notifications@github.com> wrote:
 

 The readme includes the ubuntu version that the demo has been tested with and the kernel version needed for the VXLAN-GPE drivers. You will need kernel version 3.19 for the VXLAN-GPE drivers as mentioned in the readme. https://github.com/p4lang/ntf/tree/master/apps/int—

**Comment by familysingh** [comment]
See my last email above.
