### ISSUE TITLE
WARNING: No route found for IPv6 destination :: (no default route?)

### ISSUE THREAD

**Issue by MahadevanMD** [p4lang/p4factory#152]
When i use the following steps am getting the below mentioned Error message....

To run a simple test, run this in a different terminal:
cd p4factory/targets/basic_routing/
sudo python run_tests.py --test-dir tests/ptf-tests/

Can anyone give a solution. Thank you in advance.

~/p4factory/targets/basic_routing$ sudo python run_tests.py --test-dir tests/ptf-tests/
WARNING: No route found for IPv6 destination :: (no default route?)
routing.TwoBdLpmTest ... ERROR

======================================================================
ERROR: routing.TwoBdLpmTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/maha/p4factory/targets/basic_routing/../../testutils/pd_base_tests.py", line 65, in setUp
    ThriftInterface.setUp(self)
  File "/home/maha/p4factory/targets/basic_routing/../../testutils/pd_base_tests.py", line 49, in setUp
    self.transport.open()
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 149, in open
    return self.__trans.open()
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 101, in open
    message=message)
TTransportException: Could not connect to localhost:9090

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)

******************************************
ATTENTION: SOME TESTS DID NOT PASS!!!

The following tests errored:
TwoBdLpmTest

******************************************

**Comment by antoninbas** [comment]
`WARNING: No route found for IPv6 destination :: (no default route?)` is not really an error here.
`TTransportException: Could not connect to localhost:9090` on the other hand is a real error, and usually means that you do not have the switch running. Which command did you use to start the behavioral model switch?

**Comment by antoninbas** [comment]
BTW, the steps described in the README are as follows:
```
cd p4factory/targets/basic_routing/
make bm
sudo ./behavioral-model
```
You want to make sure that `sudo ./behavioral-model` did not return an error.

**Comment by MahadevanMD** [comment]
First of all, Thank you for your answering.
When i start behavioral model itself getting errors are below

~/p4factory/targets/basic_routing$ make bm
cp /home/maha/p4factory/targets/basic_routing/build//bin/bm behavioral-model
cp: cannot create regular file ‘behavioral-model’: Permission denied
/home/maha/p4factory/targets/basic_routing/../../makefiles/bm.mk:115: recipe for target 'bm' failed
make: *** [bm] Error 1

/p4factory/targets/basic_routing$ sudo ./behavioral-model 

No PD RPC server address specified, using 127.0.0.1:9090
No listener specified, switch will run in standalone mode

P4 Program:  basic_routing

Starting RPC server on port 9090
bmi_port_interface_add(port_mgr, veth_name, n_veth, pcap_filename): ERROR -1 at main.c:434

Can you give the solution for the above mentioned error??

**Comment by antoninbas** [comment]
The `make` error could mean that the file is busy because another instance is running.
For the `bmi_port_interface_add` error, you need to run `sudo p4factory/tools/veth_setup.sh` as indicated in the `README`. It will create the veth interfaces needed to run the model.
