### ISSUE TITLE
feeding bmv2 switch with own JSON

### ISSUE THREAD

**Issue by cw299** [p4lang/p4factory#157]
When I try to launch the target switch https://github.com/p4lang/p4factory/tree/master/targets/switch/bmv2  with my own JSON file (`my_program.json` instead by given `switch_bmv2.json`) I get the following error message: 

> lt-simple_switch: ../../include/bm/bm_sim/bytecontainer.h:95: bm::ByteContainer::ByteContainer(const string&): Assertion `(size - idx) > 0' failed.

The JSON file is generated by command: ` p4c-bmv2 my_program.p4 --json my_program.json`

The switch is started by command: `sudo ./switch_bmv2 --log-console -i 0@veth0 -i 1@veth2 -i 2@veth4 -i 3@veth6 -i 4@veth8 -i 5@veth10 -i 6@veth12 -i 7@veth14 -i 8@veth16 -i 64@veth250 --thrift-port 10001 --pcap  my_program.json`. This command produces the error message.

Is it not possible to feed this bmv2 switch with my own p4 program?

**Comment by antoninbas** [comment]
If you are going to use your own P4 program / own JSON; I would not recommend using p4factory. p4factory points to a specific version of p4c-bm and simple_switch (i.e. bmv2); they don't get updated very frequently. If you use a recent version of p4c-bm and the p4factory version of bmv2 (which seems to be what you are doing here), you may experience issues.
If you are using the latest versions of p4c-bm and bmv2, and you still observe an issue when loading the JSON, please report an issue for the behavioral-model repo.
