### ISSUE TITLE
When I fellow the step in ReadMe: ./autogen.sh, I found a problem

### ISSUE THREAD

**Issue by Wasdns** [p4lang/p4factory#161]
![](http://od690gqhu.bkt.clouddn.com/2016923173632.png)
The command failed... 

I tried the command `chmod -777 /home/wasdns/p4factory-master/submodules` and `sudo dos2unix p4factory-master/autogen.sh` but it didn't work...

Can someone help me? Thanks!

The content of autogen.sh:
```
cd submodules/switch/ && ./autogen.sh && cd -
cd submodules/bm/ && ./autogen.sh && cd -
cd submodules/p4-build/ && ./autogen.sh && cd -
cd submodules/p4ofagent && ./autogen.sh && cd -
```

**Comment by antoninbas** [comment]
You need to run `git submodule update --init --recursive` after cloning the repo and before running `autogen.sh`
