### ISSUE TITLE
targets/basic_routing

### ISSUE THREAD

**Issue by peiqiaoWang** [p4lang/p4factory#163]
When the first installation,I follow the README.
`cd p4factory/targets/basic_routing/
make bm
sudo ./behavioral-model`
It is successful. 
But today,I want to do the same thing,use these code
`sudo ./behavioral-mode`
error
`wpq@wpq-VirtualBox:~/p4factory/targets/basic_routing$ sudo ./behavioral-model 
No PD RPC server address specified, using 127.0.0.1:9090
No listener specified, switch will run in standalone mode

P4 Program:  basic_routing

Starting RPC server on port 9090
bmi_port_interface_add(port_mgr, veth_name, n_veth, pcap_filename): ERROR -1 at main.c:434wpq@wpq-VirtualBox:~/p4factory/targets/basic_routing$ 
`

thx

**Comment by antoninbas** [comment]
Every time you restart your machine, you need to create the veth interfaces again using the script under `tools`. Otherwise you get the error you are seeing because the switch cannot connect to any interface.
