### ISSUE TITLE
targets/basic_routing

### ISSUE THREAD

**Issue by wangxiaolon** [p4lang/p4factory#167]
When the first installation,I follow the README.
cd p4factory/targets/basic_routing/ 
make bm
p4c_bm/shell.py", line 20, in<module>
  from p4_hlir.main import HLIR
ImportError:No module named p4_hlir.main
make:***[bm_tenjin_output_oldest]
I am sure "p4_hlir" have been cloned in submodules successfully .
could you give me some instructions? Thank you!

**Comment by antoninbas** [comment]
Hi,

I don't see a `p4_hlir` in the submodules, so I am not sure what you are referring to. This repository assumes that p4-hlir has been installed, just like in this script: https://github.com/p4lang/p4factory/blob/master/install_deps.sh#L101

Finally, I notice that you are using the first version of the behavioral model here (bmv1), we are planning on deprecating it soon in favor of bmv2 (https://github.com/p4lang/behavioral-model). See here for more details: https://github.com/p4lang/p4factory#towards-a-better-behavioral-model-bmv2
