### ISSUE TITLE
Could not connect to 127.0.0.1:9090/22222 in simple_router

### ISSUE THREAD

**Issue by realmanhw** [p4lang/p4factory#178]
The first time I ran **simple_route**, it workd well. But after I restart the machine, when running **run_demo.bash**, it worked, then I try to run **run_cli.bash**, there is a error

> •root@iZ2zec18vwwtn1ixn4g4dqZ:/home/p4factory/targets/simple_router# ./run_cli.bash
>  Using default thrift server and port localhost:9090
>  Traceback (most recent call last):
>  File "../../cli/pd_cli.py", line 677, in 
>  main(sys.argv[1:])
>  File "../../cli/pd_cli.py", line 665, in main
>  pd_cli = PdCli(p4_name, thrift_client_module, thrift_server, port)
>  File "../../cli/pd_cli.py", line 35, in init
>  self._thrift_client = pd_thrift_client.ThriftClient(self._module, thrift_server, port, self._p4_name)
>  File "/home/p4factory/cli/pd_thrift_client.py", line 55, in init
>  self.setup(hostname, port)
>  File "/home/p4factory/cli/pd_thrift_client.py", line 77, in setup
>  self._transport.open()
>  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 149, in open
>  return self.__trans.open()
>  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 101, in open
>  message=message)
> **_thrift.transport.TTransport.TTransportException: Could not connect to localhost:9090_**

And when I tried other port like 22222, 11111, there is the same error Could not connect to……

Then, I ran **./behavioral-model**, there is also a error

> •No PD RPC server address specified, using 127.0.0.1:9090
>  No listener specified, switch will run in standalone mode
>  P4 Program: simple_router
>  Starting RPC server on port 9090
>  **bmi_port_interface_add(port_mgr, veth_name, n_veth, pcap_filename): ERROR -1 at main.c**:430root@iZ2zec18vwwtn1ixn4g4dqZ:/home/p4factory/targets/simple_router#

Does anyone know how to deal with it? Thanks!

**Comment by antoninbas** [comment]
When you restart your machine, you need to create the veth interfaces again, by running the `veth_setup.sh` script.
