### ISSUE TITLE
add table entries for multiple switches. 

### ISSUE THREAD

**Issue by haseebnaseem** [p4lang/p4factory#190]
Hi, I am trying work with a three switch topology. I know how to add table entries for one switch using the ./run_add_entries.sh script. I understand that it uses a port number to identify a switch which is 22222 by default. I created the other switches with port number 22223 and 22224 respectively. When I set the port number to 22223 using the '-c' tag, this error shows `TTransportException: Could not connect to any of [('127.0.0.1', 22223)]` can anyone please help ?

**Comment by antoninbas** [comment]
This repo is mostly deprecated, so I wouldn't recommend using it anymore. Which P4 program are you trying to run?

**Comment by haseebnaseem** [comment]
I'm trying to implement ECMP using p4.

**Comment by antoninbas** [comment]
My advice is to look at this P4 tutorial if you haven't yet: https://github.com/p4lang/tutorials/tree/master/workshop_05_2016/ecmp
In any case, you do not need this repo, you should use bmv2 directly: https://github.com/p4lang/behavioral-model
If you need help with something specific, please send an email to the p4-dev mailing list (http://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org)

**Comment by haseebnaseem** [comment]
I did look at the ecmp workshop to have an idea about how I should go about it, however I want to evaluate the performance of ecmp on custom topologies which, I think, isn't possible with the workshop example.

**Comment by antoninbas** [comment]
You should adapt the P4 program to your own needs. However I would recommend using the same tools as the tutorial (bmv2, bmv2 CLI, Mininet topology script). The code in p4factory is hardly maintained any more.

**Comment by haseebnaseem** [comment]
Thank you so much for your suggestion, I guess I will look towards bmv2 since I've hit a dead end here.
