### ISSUE TITLE
make bm error

### ISSUE THREAD

**Issue by li7hui** [p4lang/p4factory#206]
hello,

i meet the following error when "make bm" in [p4factory/targets/basic_routing

![makebm](https://user-images.githubusercontent.com/1718938/43059948-6e5b3048-8e81-11e8-93d0-251e156ed30c.png)

please help

**Comment by antoninbas** [comment]
As stated in the main README, this repo is being deprecated, so please use bmv2 instead to experiment with P4: https://github.com/p4lang/behavioral-model
In this specific case, it looks like you have the wrong version of Thrift (we support 0.9.2 and 0.9.3).
