### ISSUE TITLE
issues with creating docker image,vxlan driver 

### ISSUE THREAD

**Issue by akshara01** [p4lang/p4factory#208]
I have attached the images of the issues faced

![1 1 issue while building docker image](https://user-images.githubusercontent.com/89603333/136986163-f170a6db-e087-4ccb-befb-dc67ab0a5664.PNG
![1 2](https://user-images.githubusercontent.com/89603333/136986271-99e483b1-4246-4afb-8770-2fa4e3ae6d3d.PNG)
)
![1 3](https://user-images.githubusercontent.com/89603333/136986289-3b9b63eb-904f-457d-91c9-f861be0f2e6f.PNG)

**Comment by dhrumilp7255** [comment]
Yes , I was also doing the same and encountered this problem , any one please help for further set up process

**Comment by antoninbas** [comment]
As indicated in the README, this repo has not been maintained for 4 years. I doubt anyone is going to provide help.
There are other, supported ways to run the p4lang software.

**Comment by akshara01** [comment]
Could you suggest some other supported platforms for performing INT

**Comment by dhrumilp7255** [comment]
Yes , Can you please suggest some other ways to implement INT?

**Comment by antoninbas** [comment]
I think the ONF's fabric.p4 program comes with an INT implementation (https://github.com/opennetworkinglab/onos/blob/master/pipelines/fabric/impl/src/main/resources/fabric.p4) with the ONOS controller providing the control plane implementation (I think they have an INT app for ONOS). You should reach out to them on their slack to get some information.

Ideally there would be SAI INT support but I don't think the proposal went anywhere (?): https://github.com/opencomputeproject/SAI/tree/master/doc/DTEL

Finally, you can reach out to the P4 Applications Working Group to get some recommendations: https://p4.org/working-groups/
