### ISSUE TITLE
Thrift RPC Exception

### ISSUE THREAD

**Issue by anubhavnidhi** [p4lang/p4factory#34]
I tried the "Integration with Mininet" example of P4. When I enter "./run_add_demo_entries.bash", I get a thrift exception

> > thrift.transport.TTransport.TTransportException: Could not connect to localhost:22222
> > Traceback (most recent call last):
> >   File "../../cli/pd_cli.py", line 691, in <module>
> >     main(sys.argv[1:])
> >   File "../../cli/pd_cli.py", line 679, in main
> >     pd_cli = PdCli(p4_name, thrift_client_module, thrift_server, port)
> >   File "../../cli/pd_cli.py", line 35, in **init**
> >     self._thrift_client = pd_thrift_client.ThriftClient(self._module, thrift_server, port, self._p4_name)
> >   File "/home/mininet/p4/p4factory/cli/pd_thrift_client.py", line 55, in __init__
> >     self.setup(hostname, port)
> >   File "/home/mininet/p4/p4factory/cli/pd_thrift_client.py", line 77, in setup
> >     self._transport.open()
> >   File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 149, in open
> >     return self.__trans.open()
> >   File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 101, in open
> >     message=message)
> > thrift.transport.TTransport.TTransportException: Could not connect to localhost:22222

When I entered the following command

> > home/mininet/p4/p4factory/targets/simple_router/behavioral-model --name s1 --dpid 0000000000000001 -i s1-eth1 -i s1-eth2 --listener 127.0.0.1:11111 --pd-server 127.0.0.1:22222

I get the following message

> > PD server address is 127.0.0.1:22222
> > P4 Program:  simple_router
> > Starting RPC server on port 22222
> > No p4nsdb address specified, using 127.0.0.1:6379
> > Connected to P4NS DB
> > P4NSDB: could not create datapath, s1 already exists

Do you know what I am doing wrong?

**Comment by antoninbas** [comment]
Yes, it means mininet did not exit properly the previous time, or you have another instance of behavioral-model running. Try the following:
sudo mn -c
sudo killall behavioral-model
redis-cli FLUSHALL

**Comment by rahulbhalerao001** [comment]
I too was facing the same issue. Thank you for the solution.

**Comment by lmingcsce** [comment]
I encounter the same issue. 
Thanks.

**Comment by Hamkuu** [comment]
I had the same issue and solved it by: 
```
sudo mn -c
sudo killall behavioral-model
redis-cli FLUSHALL
```
However, when I run "./run_cli.bash" under "p4factory/targets/simple_router", I got TTransportException, how can I fix this?

> Using default thrift server and port localhost:9090
Traceback (most recent call last):
  File "../../cli/pd_cli.py", line 677, in <module>
    main(sys.argv[1:])
  File "../../cli/pd_cli.py", line 665, in main
    pd_cli = PdCli(p4_name, thrift_client_module, thrift_server, port)
  File "../../cli/pd_cli.py", line 35, in __init__
    self._thrift_client = pd_thrift_client.ThriftClient(self._module, thrift_server, port, self._p4_name)
  File "/home/hamkuu/p4/p4factory/cli/pd_thrift_client.py", line 55, in __init__
    self.setup(hostname, port)
  File "/home/hamkuu/p4/p4factory/cli/pd_thrift_client.py", line 77, in setup
    self._transport.open()
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 149, in open
    return self.__trans.open()
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 101, in open
    message=message)
thrift.transport.TTransport.TTransportException: Could not connect to localhost:9090

**Comment by antoninbas** [comment]
Did you start the software switch? What was the output for this?

**Comment by shahbhoomi** [comment]
Hi I am trying to add demo entries to the switch.
I did the following procedure:
From the terminal, add entries in the switch:
/p4factory/targets/simple_router$ more run_add_demo_entries.bash
and then ./run_add_demo_entries.bash
I tried using the above three commands given for killing the behavioral process and exiting the mining but still I am getting the same error.
Can you please help me out on where am I going wrong?
![screen shot 2016-06-15 at 11 08 08 pm](https://cloud.githubusercontent.com/assets/16211732/16104377/a15d1ffa-334e-11e6-9d85-3db348d72357.png)

**Comment by antoninbas** [comment]
You did not show how you started the switch in your screenshot.
We are also deprecating this software switch and replacing it with bmv2. I encourage you to look at these repositories:
- the new bmv2 software switch: https://github.com/p4lang/behavioral-model
- tutorials and examples: https://github.com/p4lang/tutorials

**Comment by sandaruwanjayaweera** [comment]
I had the same issue which [hamkuu](https://github.com/hamkuu) had. Then I changed run_cli.bash,
`python ../../cli/pd_cli.py -p simple_router -i p4_pd_rpc.simple_router -s $PWD/tests/pd_thrift:$PWD/../../testutils "$@"`
into
`python ../../cli/pd_cli.py -p simple_router -i p4_pd_rpc.simple_router -s $PWD/tests/pd_thrift:$PWD/../../testutils "$@" -c localhost:22222`
to provide the CLI with the port. After that it worked fine.

**Comment by XingguoTian** [comment]
./run_cli.bash -c 127.0.0.1:22222 ,this will solve your problem  @hamkuu

**Comment by LLRH** [comment]
root@wenxingbeng:/home/wenxingbeng/p4factory# redis-cli FLUSHALL
Could not connect to Redis at 127.0.0.1:6379: Connection refused
