### ISSUE TITLE
Error while running l2_switch example

### ISSUE THREAD

**Issue by pavanrai123** [p4lang/p4factory#80]
Hi all,
I am getting below errors while running l2_switch example

[root@localhost l2_switch]# make bm
    Linking: bm
/usr/bin/ld: cannot find -ledit
collect2: error: ld returned 1 exit status
/home/prai/p4factory/targets/l2_switch/../../makefiles/bin.mk:29: recipe for target '/home/prai/p4factory/targets/l2_switch/build//bin/bm' failed
make: *** [/home/prai/p4factory/targets/l2_switch/build//bin/bm] Error 1

Thanks,
Pavan

**Comment by antoninbas** [comment]
It seems to me that installing the libedit library should solve the problem (`sudo apt-get install libedit-dev` on Ubuntu).

**Comment by pavanrai123** [comment]
Thanks antoninbas it works
