### ISSUE TITLE
thrift not found when making a docker image for switch

### ISSUE THREAD

**Issue by Hamkuu** [p4lang/p4factory#86]
I was trying to setup the environment instructed by [reference implementation of the Inband Network Telemetry](https://github.com/p4lang/p4factory/tree/master/apps/int).

However, when I build a docker image for the switch:
```
make docker-image
```
After a few minutes' running, I got these errors:
> thrift -r --gen cpp --out /p4factory/targets/switch/build//bm/src /p4factory/targets/switch/build//bm/thrift/p4_pd_rpc.thrift &&  thrift -r --gen cpp --out /p4factory/targets/switch/build//bm/src /p4factory/targets/switch/build//bm/thrift/conn_mgr_pd_rpc.thrift &&  thrift -r --gen cpp --out /p4factory/targets/switch/build//bm/src /p4factory/targets/switch/build//bm/thrift/mc_pd_rpc.thrift &&  true
/bin/sh: 1: thrift: not found
make: *** [/p4factory/targets/switch/build//bm/src/p4_pd_rpc_types.h] Error 127
make: *** Waiting for unfinished jobs....
The command '/bin/sh -c cd /p4factory ; ./autogen.sh ; ./configure ; cd /p4factory/targets/switch ; make clean ; make -j4 bm-switchlink' returned a non-zero code: 2
make: *** [docker-image] Error 1

I had installed the [dependencies](https://github.com/p4lang/p4factory/blob/master/install_deps.sh), and cloned [p4lang/thrift](https://github.com/p4lang/thrift), installed and checked.

**Comment by antoninbas** [comment]
Hi,

Did you install all the dependencies listed here: https://github.com/p4lang/p4factory/blob/master/install_deps.sh
Thrift is one of these dependencies.

**Comment by Hamkuu** [comment]
@antoninbas yes, I had installed those dependencies

**Comment by antoninbas** [comment]
I think that thrift is installed fine on your laptop / VM, but not in the docker.
The Dockerfile (https://github.com/p4lang/p4factory/blob/master/docker/Dockerfile#L42) takes care of installing thrift in the docker when creating it. It is possible that something went wrong. We can find out if you send the full output of `make docker-image`. Could you paste the output on any online service and then share the link here ? Or alternatively send it as an attachment to the p4-dev mailing list?

**Comment by Hamkuu** [comment]
@antoninbas here is the [full output of make docker-image](https://www.dropbox.com/s/f50kz7ah4z8fe5a/output-of-make-docker-image.txt?dl=0)

**Comment by jaepark** [comment]
I think you are not using the most recent version. This problem was fixed in https://github.com/p4lang/p4factory/commit/e7aef3e3d723c0a21a0d7e52ec21a2d51f26f1c6

**Comment by antoninbas** [comment]
Yes, your output shows that you are using http://www.gtlib.gatech.edu/pub/apache/thrift/0.9.1/thrift-0.9.1.tar.gz, which is no longer a valid link. The error will go away if you update p4factory (don't forget to update the submodules):
```
git pull origin master
git submodule update --init --recursive
```

**Comment by Muthuramane** [comment]
I am also faced same issue what hamkuu reported here.

Could you please any one tell me how to fix that issue.

If you need my system logs then please tell me.

**Comment by antoninbas** [comment]
Your logs show don't show any error when installing thrift. However, the docker build is using a cached image, so we don't get full logs. Could you try to build an image without using the cache?
I believe this can be done by adding `-no-cache` to `docker build`. Alternatively you probably can delete all docker images and containers present on your system.
You could also try to log in the docker image and try to debug the Thrift installation.
