### ISSUE TITLE
Problem on building the docker image

### ISSUE THREAD

**Issue by Hamkuu** [p4lang/p4factory#90]
My testing OS is ubuntu-14.04.3-desktop-amd64.

I followed every steps to setup the environment, and repeat several times, but always stuck on building the docker image.

After I run:
```
make docker-image
```
it executed for a while, and stuck after these output:
```
    Compiling : bm::p4_pd_rpc_constants.cpp
    Compiling : bm::conn_mgr_pd_rpc_constants.cpp
    Compiling : bm::mc_pd_rpc_constants.cpp
    Compiling : bm::res_constants.cpp
    Compiling : bm::p4_pd_rpc_types.cpp
    Compiling : bm::conn_mgr_pd_rpc_types.cpp
    Compiling : bm::mc_pd_rpc_types.cpp
    Compiling : bm::res_types.cpp
    Compiling : bm::dc.cpp
    Compiling : bm::conn_mgr.cpp
    Compiling : bm::mc.cpp
Copying python thrift files
WARNING: No libraries specified
INFO: Status: Preprocessing /tmp/tmp4uucfo.h
INFO: Status: gcc -E -U __GNUC__ -dD -I/usr/include -I/p4factory/submodules/switchsai/submodules/ocpsai/sai/inc "-Dinline=" "-D__inline__=" "-D__extension__=" "-D__const=const" "-D__asm__(x)=" "-D__asm(x)=" "-DCTYPESGEN=1" "/tmp/tmp4uucfo.h"
INFO: Status: Parsing /tmp/tmp4uucfo.h
INFO: Status: Processing description list.
WARNING: Macro "SAI_MAX_FIRMWARE_PATH_NAME_LEN" depends on an unknown identifier "PATH_MAX". Macro "SAI_MAX_FIRMWARE_PATH_NAME_LEN" will not be output
INFO: Status: Writing to /p4factory/targets/switch/tests/pd_thrift/switch_sai_thrift/sai_headers.py.
INFO: Status: Wrapping complete.
```
I waited for hours, no any further progress

**Comment by Hamkuu** [comment]
I did clone the p4factory repository and run:
->git submodule update --init --recursive

**Comment by antoninbas** [comment]
Hi,
Could you check that the compiler is still running (with `top`)? Also, how much memory did you allocate to the VM (or is available on your system if you are running Ubuntu natively)?

**Comment by Hamkuu** [comment]
@antoninbas 
Thanks for your suggestion.
I found the process was still running, it just ran much much longer than I expected.
The environment was setup successfully for the INT application, eventually.

**Comment by antoninbas** [comment]
The build process can run for pretty long, especially if you don't have much memory. You can speed things up by assigning more resources to your VM.
