### ISSUE TITLE
Any instructions on how to use p4dockerswitch image?

### ISSUE THREAD

**Issue by hamkuu** [p4lang/p4factory#94]
I followed the README file under p4lang/p4factory and built the  p4dockerswitch image successfully.

But I cannot find any instruction how to play with it.

**Comment by antoninbas** [comment]
The switch target README (https://github.com/p4lang/p4factory/tree/master/targets/switch#running-tests) gives some information on how to run the docker tests.
I believe every test script contains some information about which network topology the test is using (e.g https://github.com/p4lang/p4factory/blob/master/mininet/swl_l2.py#L18).

**Comment by hamkuu** [comment]
@antoninbas Thanks for your suggestion.

I studied the [switch target README file](https://github.com/p4lang/p4factory/tree/master/targets/switch#switchp4) several times and built the soft switch under different command.(as suggested in [#building-soft-switch](https://github.com/p4lang/p4factory/tree/master/targets/switch#building-soft-switch))

I got a question on [#building-soft-switch](https://github.com/p4lang/p4factory/tree/master/targets/switch#building-soft-switch):

Except for docker-image building command:
```
make docker-image
```
Is that the soft-switches built under different make command cannot coexist with one another? Because the "behavioral-model" file seems to be overwritten each time I ran different make command.

And another question on [#running-tests](https://github.com/p4lang/p4factory/tree/master/targets/switch#running-tests):

```
sudo ./run_tests.py --test-dir tests/ptf-tests/pd-tests switch
```
What does "switch" mean in this command? Should I change it under specific circumstance?
