### ISSUE TITLE
no autogen.sh in submodules sub-directories !!!!!

### ISSUE THREAD

**Issue by ali64Mon** [p4lang/p4factory#98]
Hi, 

I'm new to P4. I'm trying to install p4factory. however, when I try to run ''./autogen.sh " I encounter the following errors:
./autogen.sh: 1: ./autogen.sh: ./autogen.sh: not found
./autogen.sh: 2: cd: can't cd to submodules/bm/
./autogen.sh: 3: cd: can't cd to submodules/p4c-bm/pd_mk/
./autogen.sh: 4: cd: can't cd to submodules/p4ofagent

If fact, there is no autogen.sh file in submodules sub-directories. 
I have already ran ./install_deps.sh and sudo p4factory/tools/veth_setup.sh commands.

Any idea?

**Comment by antoninbas** [comment]
Are you sure you ran `git submodule update --init --recursive`. It is at the very beginning of the README.

**Comment by ali64Mon** [comment]
Thanks. I ran the git command and it is fixed now.

**Comment by jjkim12** [comment]
Hello,

I'm a newer both ubuntu and git utilities.
(I think something I missed)

I've same issue with you.
Could you share your " git submodule update --init --recursive " result.
My system information and excution log is these are....

root@ubuntu:/home/ubuntu/download/p4factory-master# uname -a
Linux ubuntu 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

1. # unzip master
2. # cd p4factory-master
3. # git init
     initialized existing Git repository in /home/ubuntu/download/p4factory-master/.git/
4. # git submodule update --init --recursive
      ...nothing.... // I think this should show something package get...
5. # ./install_deps.sh
    package get...and install ....including thrift....

6. # ./autogen.sh
./autogen.sh: line 1: ./autogen.sh: No such file or directory
./autogen.sh: line 2: cd: submodules/bm/: No such file or directory
./autogen.sh: line 3: cd: submodules/p4-build/: No such file or directory
./autogen.sh: line 4: cd: submodules/p4ofagent: No such file or directory
root@ubuntu:/home/ubuntu/download/p4factory-master#

**Comment by antoninbas** [comment]
The repository has submodules and therefore you cannot use the "download .zip" option from Github. You have to clone the repository instead. For example: git clone https://github.com/p4lang/p4factory.git.
The .zip option will lose the information about the submodules.

**Comment by jjkim12** [comment]
Thanks Antoninbas.

Just before I success autogen.sh and confiure.
It seems work fine.
